---
jobs:
  - name: "updates-abs"
    serial: true
    plan:
      - get: "timer-1h"
        trigger: true
      - get: "docker-archlinux-base"
        trigger: true
        params:
          skip_download: true
      - get: git-archlinux-abs
      - task: "check-abs-updates"
        file: "git-archlinux-abs/check-package-updates.yml"
      - put: "base-notify"

  - name: "updates-base"
    serial: true
    plan:
      - get: "base-notify"
        trigger: true
        params:
          skip_download: true
      - task: "check-base-updates"
        file: "git-archlinux-abs/check-base.yml"
      - put: "build-notify"

  - name: "build-image"
    plan:
      - get: "build-notify"
        trigger: true
      - get: git-archlinux-abs
      - put: "docker-archlinux-abs"
        params:
          build: "git-archlinux-abs"
          build_args:
        get_params:
          skip_download: true

resources:
  - name: "timer-1h"
    type: "time"
    source:
      interval: "1h"

  - name: "git-archlinux-abs"
    type: "git"
    source:
      uri: "git@github.com:stingA0815/docker-archlinux-abs.git"
      branch: "master"
      private_key: {{github_private_key}}

  - name: "docker-archlinux-abs"
    type: "docker-image"
    source:
      email: {{dockerhub_email}}
      username: {{dockerhub_user}}
      password: {{dockerhub_pw}}
      repository: "stinga0815/archlinux-abs"

  - name: "docker-archlinux-base"
    type: "docker-image"
    source:
      email: {{dockerhub_email}}
      username: {{dockerhub_user}}
      password: {{dockerhub_pw}}
      repository: "stinga0815/archlinux-base"

  - name: "base-notify"
    type: "dummy"

  - name: "build-notify"
    type: "dummy"



resource_types:
  - name: dummy
    type: docker-image
    source:
      repository: "stinga0815/concourse-dummy-resource"
